name: Gets boxes checked
on: [pull_request]

jobs:
  get-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checks body
        uses: JJ/pull-request-checks-action@main
      - name: Shows result
        run: echo ${GITHUB_ENV}
