name: 'get-pr-checks'
on: [pull_request]

jobs:
  get-checks: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: JJ/pull-request-checks-action@releases/v1
      - name: Check output
        run: echo ${checked}
