name: Gets boxes checked
on: [pull_request]

jobs:
  get-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checks body
        id: pr_body_checks
        uses: JJ/pull-request-checks-action@main
      - name: Shows result
        env:
          OUTPUTS: ${{join(steps.pr_body_checks.outputs.*, '\n')}}
        run: echo OUTPUTS && echo META
