name: 'get-pr-checks'
on: [pull_request]

jobs:
  get-checks: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - name: Checks body
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const checklist = /\s*-\s+\[\s*([xX]?)\s*\]\s+(.+?)\.\s+/gm
            if ( !context.payload.pull_request ) {
              core.setFailed("Only available for pull requests")
            }
            const body: string = context.payload.pull_request.body!
            console.log( body )
            let checked = {}
            let match = checklist.exec(body)
            while (match != null) {
              checked[match[2]] = match[1]?true:false
              match = checklist.exec(body)
            }
            console.log("::set-output name=checked::${checked}")

