name: Obtain values for checklist
on: [pull_request, pull_request_target]

jobs:
  get-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Verifies checklist in PR body
        id: pr_body_checks
        uses: JJ/pull-request-checks-action@main
      - name: Shows result
        env:
          IS_EXCLUDED_USER: ${{ steps.pr_body_checks.outputs.isExcludedUser }}
          CONTRIBUTING: ${{ steps.pr_body_checks.outputs.CONTRIBUTING }}
        run: echo "Values $CONTRIBUTING - $IS_EXCLUDED_USER - $isExcludedUser"
      - name: Checking CONTRIBUTING is compulsory
        if: ${{ ! steps.pr_body_checks.outputs.isExcludedUser == 'true' && steps.pr_body_checks.outputs.CONTRIBUTING == 'false'}}
        run: echo "Please read CONTRIBUTING.md" && exit 1
