name: Obtain values for checklist
on: [pull_request]

jobs:
  get-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Verifies checklist in PR body
        id: pr_body_checks
        uses: JJ/pull-request-checks-action@main
      - name: Shows result
        run: echo $CONTRIBUTING && echo $check0
      - name: Contributing is compulsoryç
        if: ${{ steps.pr_body_checks.outputs.CONTRIBUTING == false}}
        run: echo "Please read CONTRIBUTING.md" && exit 1
